# Generated by Django 3.2 on 2021-05-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_user', models.CharField(default=None, max_length=16)),
                ('admin_pwd', models.CharField(default=None, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=20)),
                ('Stu_sex', models.CharField(max_length=10)),
                ('Stu_ID', models.BigIntegerField(default=0)),
                ('Stu_pro', models.CharField(max_length=30)),
                ('Stu_code', models.BigIntegerField(default=0)),
                ('Tel_No', models.BigIntegerField(default=0)),
                ('Email', models.CharField(max_length=40)),
                ('Stu_age', models.IntegerField(default=0)),
                ('Stu_place', models.CharField(max_length=25)),
            ],
        ),
    ]
